---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-rc
  namespace: test-ns
  labels:
    app: mysql-data
    author: maruti
spec:
  replicas: 2
  template:
    metadata:
      name: mysql-pod
      labels:
        type: mysql-database
    spec:
      containers:
        - name: mysql-container
          image: mysql
          ports:
            - containerPort: 3306
              hostPort: 8082
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: maruti
...
