---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  namespace: test-ns
  labels:
    app: httpd-app
    author: maruti
spec:
  containers:
    - name: httpd-app
      image: httpd
      ports:
        - containerPort: 80
          hostPort: 8081
...
