---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-simple-pod
  labels:
    type: nginx
    author: maruti
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 8080
...
